# Generated by Django 5.0 on 2024-01-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0004_alter_posting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=250, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='phone'),
        ),
    ]
