# Generated by Django 5.0 on 2024-01-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0005_user_address_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='content',
            field=models.TextField(),
        ),
    ]
